apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
  - image: rbinrais/healthcheck
    name: liveness-probe
    livenessProbe:
      httpGet:
        path: /
        port: 8080
